version: '3.9'

name: elvis

x-base_elvis: &base_elvis
  image: elvis:build
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - GITHUB_TOKEN=${GITHUB_TOKEN:?GITHUB_TOKEN is required}
      - PLUGINS_LIST_DOWNLOAD_URL=${PLUGINS_LIST_DOWNLOAD_URL}
  environment:
    - Rails_ENV=kubernetes
    - INSTANCE_NAME=${INSTANCE_NAME:-elvis}
    - STORAGE_ACCOUNT=${STORAGE_ACCOUNT:-local}
    - RAILS_LOG_TO_STDOUT=true
    - RAILS_SERVE_STATIC_FILES=true
    - ELVIS_DB=${POSTGRES_DB_NAME:-elvis}
    - ELVIS_DB_USER=${POSTGRES_DB_USER:-postgres}
    - ELVIS_DB_PASS=${POSTGRES_DB_PASS:-12345678}
    - ELVIS_DB_HOST=${POSTGRES_DB_HOST:-database}
    - ELVIS_DB_PORT=${POSTGRES_DB_PORT:-5432}
    - ELVIS_DB_SSLMODE=${POSTGRES_DB_SSLMODE:-disable}
    - ES_DB_HOST=${ELASTICSEARCH_HOST:-http://elasticsearch:9200}
    - PLUGINS_LIST_DOWNLOAD_URL=${PLUGINS_LIST_DOWNLOAD_URL}
    - ES_PREFIX=elvis
    - RAILS_SERVE_STATIC_FILES=true
    - REDIS_URL=redis://redis:6379/0
    - USE_REDIS_FOR_CACHING=true
    - RAILS_PERFORMANCE_ENABLED=true
    - RAILS_PERFORMANCE_PASSWORD=${RAILS_PERFORMANCE_PASSWORD:-12345678}
    - RAILS_PERFORMANCE_USER=${RAILS_PERFORMANCE_USER:-admin}
    - RAILS_PERFORMANCE_DURATION=${RAILS_PERFORMANCE_DURATION:-48}
    - RACK_MINI_PROFILER=true
    - RACK_MINI_PROFILER_REDIS_URL=redis://redis:6379/1
    - USE_SIDEKIQ=true
  networks:
    - elvis
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  elvis_init:
    <<: *base_elvis
    container_name: elvis_init
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      database:
        condition: service_healthy
    entrypoint: "./entrypoints/init.sh"

  elvis:
    <<: *base_elvis
    container_name: elvis
    depends_on:
      elvis_init:
        condition: service_completed_successfully
    ports:
      - "7212:80"
    healthcheck:
      test: curl -s http://localhost:80/ping >/dev/null || exit 1
      interval: 10s
      timeout: 3s
      retries: 10

  sidekiq:
    <<: *base_elvis
    container_name: sidekiq
    depends_on:
      redis:
        condition: service_healthy
      elvis_init:
        condition: service_completed_successfully
    entrypoint: bundle exec sidekiq -C config/sidekiq.yml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - elvis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - elvis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    profiles:
      - redisinsight
    container_name: redis-insight
    volumes:
      - redisinsight_data:/data
    ports:
      - '5540:5540'
    networks:
      - elvis
    depends_on:
      redis:
        condition: service_healthy

  database:
    image: postgres:14.0
    container_name: database
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS:-12345678}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elvis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

networks:
  elvis:

volumes:
  postgres_data:
  elasticsearch_data:
  redisinsight_data: