local:
    service: Disk
    root: <%= Rails.root.join("storage") %>

test:
    service: Disk
    root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["AWS_REGION"] %>
  bucket: <%= ENV["AWS_BUCKET"] %>

azure:
    service: AzureStorage
    storage_account_name: <%= ENV["AZURE_STORAGE_ACCOUNT"] %>
    storage_access_key: <%= ENV["AZURE_STORAGE_ACCESS_KEY"] %>
    container: <%= ENV["AZURE_CONTAINER"] %>
